mysql:
  image: openzipkin/zipkin-mysql
  ports:
    - 3306:3306

query:
  image: openzipkin/zipkin
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    #- TRANSPORT_TYPE=http
    - STORAGE_TYPE=mysql
    - RABBIT_ADDRESSES=rabbitmq:5672
  ports:
    - 9411:9411
  links:
    - mysql:storage
    - rabbitmq:rabbitmq

rabbitmq:
  image: rabbitmq:management
  ports:
    - 9672:5672
    - 15672
